[package]
name = "driver-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
msfs = {git  = "https://github.com/flybywiresim/msfs-rs.git" }


[target.wasm32-wasi]
rustflags = [
    "-Clink-arg=--export-table",
    "-Clink-arg=--export=malloc",
    "-Clink-arg=--export=free",
]
